[package]
name = "sentinel-runtime"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
sentinel-common = { path = "../sentinel-common" }
anyhow = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
sentinel-common = { path = "../sentinel-common" }
