[package]
name = "sentinel-ecs"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[features]
default = []
wasm = ["sentinel-wasm/wasm"]

[dependencies]
bevy_ecs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
sentinel-common = { path = "../sentinel-common" }
sentinel-bio = { path = "../sentinel-bio" }
sentinel-physics = { path = "../sentinel-physics" }
sentinel-redb = { path = "../sentinel-redb" }
sentinel-limbo = { path = "../sentinel-limbo", default-features = false }
sentinel-wasm = { path = "../sentinel-wasm" }

[dev-dependencies]
sentinel-common = { path = "../sentinel-common" }
tempfile = "3"
toml = { workspace = true }
