[package]
name = "sentinel-hippocampus"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
redb = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
sentinel-common = { path = "../sentinel-common" }

[dev-dependencies]
approx = { workspace = true }
tempfile = "3"
criterion = { workspace = true }

[[bench]]
name = "hippocampus_bench"
harness = false
