// Statische Room-Metadata, abgeleitet aus config/rooms.toml.
// SSOT: config/rooms.toml — bei Layout-Aenderungen hier synchron halten.

import type { RoomMeta } from "./types";

export const ROOM_METADATA: Record<string, RoomMeta> = {
  empfang: {
    id: "empfang",
    name: "Empfang",
    floor: 0,
    capacity: 4,
    room_type: "common",
    adjacent: ["flur-eg", "meetingraum-01"],
  },
  "flur-eg": {
    id: "flur-eg",
    name: "Flur Erdgeschoss",
    floor: 0,
    capacity: 20,
    room_type: "transit",
    adjacent: [
      "empfang",
      "kueche",
      "buero-dev-1",
      "buero-dev-2",
      "buero-sales",
      "buero-pm",
      "buero-marketing",
      "buero-admin",
      "buero-qa",
      "buero-it",
      "meetingraum-01",
      "toilette-eg-damen",
      "toilette-eg-herren",
      "treppenhaus",
    ],
  },
  kueche: {
    id: "kueche",
    name: "Küche / Pausenraum",
    floor: 0,
    capacity: 10,
    room_type: "break",
    adjacent: ["flur-eg"],
    has_coffee_machine: true,
  },
  "buero-dev-1": {
    id: "buero-dev-1",
    name: "Entwicklungsbüro 1",
    floor: 0,
    capacity: 6,
    room_type: "office",
    adjacent: ["flur-eg", "buero-dev-2"],
    department: "Entwicklung",
  },
  "buero-dev-2": {
    id: "buero-dev-2",
    name: "Entwicklungsbüro 2",
    floor: 0,
    capacity: 6,
    room_type: "office",
    adjacent: ["flur-eg", "buero-dev-1"],
    department: "Entwicklung",
  },
  "meetingraum-01": {
    id: "meetingraum-01",
    name: "Meetingraum Galileo",
    floor: 0,
    capacity: 8,
    room_type: "meeting",
    adjacent: ["empfang", "flur-eg"],
  },
  "toilette-eg-damen": {
    id: "toilette-eg-damen",
    name: "Toilette EG Damen",
    floor: 0,
    capacity: 6,
    room_type: "bathroom",
    adjacent: ["flur-eg"],
  },
  "toilette-eg-herren": {
    id: "toilette-eg-herren",
    name: "Toilette EG Herren",
    floor: 0,
    capacity: 6,
    room_type: "bathroom",
    adjacent: ["flur-eg"],
  },
  treppenhaus: {
    id: "treppenhaus",
    name: "Treppenhaus",
    floor: -1,
    capacity: 5,
    room_type: "transit",
    adjacent: ["flur-eg", "flur-og"],
  },
  "flur-og": {
    id: "flur-og",
    name: "Flur Obergeschoss",
    floor: 1,
    capacity: 20,
    room_type: "transit",
    adjacent: [
      "treppenhaus",
      "buero-design-1",
      "buero-design-2",
      "buero-ceo",
      "buero-betriebsrat",
      "buero-betriebspsych",
      "buero-betriebsarzt",
      "meetingraum-02",
      "meetingraum-03",
      "toilette-og-damen",
      "toilette-og-herren",
    ],
  },
  "buero-design-1": {
    id: "buero-design-1",
    name: "Designbüro 1",
    floor: 1,
    capacity: 6,
    room_type: "office",
    adjacent: ["flur-og", "buero-design-2"],
    department: "Design",
  },
  "buero-design-2": {
    id: "buero-design-2",
    name: "Designbüro 2",
    floor: 1,
    capacity: 6,
    room_type: "office",
    adjacent: ["flur-og", "buero-design-1"],
    department: "Design",
  },
  "buero-ceo": {
    id: "buero-ceo",
    name: "Geschäftsführung",
    floor: 1,
    capacity: 4,
    room_type: "office",
    adjacent: ["flur-og"],
    department: "Geschäftsführung",
  },
  "meetingraum-02": {
    id: "meetingraum-02",
    name: "Meetingraum Tesla",
    floor: 1,
    capacity: 12,
    room_type: "meeting",
    adjacent: ["flur-og"],
  },
  "meetingraum-03": {
    id: "meetingraum-03",
    name: "Meetingraum Edison",
    floor: 1,
    capacity: 6,
    room_type: "meeting",
    adjacent: ["flur-og"],
  },
  "toilette-og-damen": {
    id: "toilette-og-damen",
    name: "Toilette OG Damen",
    floor: 1,
    capacity: 6,
    room_type: "bathroom",
    adjacent: ["flur-og"],
  },
  "toilette-og-herren": {
    id: "toilette-og-herren",
    name: "Toilette OG Herren",
    floor: 1,
    capacity: 6,
    room_type: "bathroom",
    adjacent: ["flur-og"],
  },
  "buero-sales": {
    id: "buero-sales",
    name: "Vertriebsbüro",
    floor: 0,
    capacity: 4,
    room_type: "office",
    adjacent: ["flur-eg"],
    department: "Vertrieb",
  },
  "buero-pm": {
    id: "buero-pm",
    name: "Projektmanagement-Büro",
    floor: 0,
    capacity: 10,
    room_type: "office",
    adjacent: ["flur-eg"],
    department: "Projektmanagement",
  },
  "buero-marketing": {
    id: "buero-marketing",
    name: "Marketingbüro",
    floor: 0,
    capacity: 4,
    room_type: "office",
    adjacent: ["flur-eg"],
    department: "Marketing",
  },
  "buero-admin": {
    id: "buero-admin",
    name: "Verwaltungsbüro",
    floor: 0,
    capacity: 8,
    room_type: "office",
    adjacent: ["flur-eg"],
    department: "Verwaltung",
  },
  "buero-qa": {
    id: "buero-qa",
    name: "QA-Büro",
    floor: 0,
    capacity: 4,
    room_type: "office",
    adjacent: ["flur-eg"],
    department: "Qualitätssicherung",
  },
  "buero-it": {
    id: "buero-it",
    name: "IT-Büro",
    floor: 0,
    capacity: 2,
    room_type: "office",
    adjacent: ["flur-eg"],
    department: "IT",
  },
  "buero-betriebsrat": {
    id: "buero-betriebsrat",
    name: "Betriebsratsbüro",
    floor: 1,
    capacity: 4,
    room_type: "office",
    adjacent: ["flur-og"],
    department: "Betriebsrat",
  },
  "buero-betriebspsych": {
    id: "buero-betriebspsych",
    name: "Betriebspsychologie",
    floor: 1,
    capacity: 4,
    room_type: "office",
    adjacent: ["flur-og"],
    department: "Gesundheit",
  },
  "buero-betriebsarzt": {
    id: "buero-betriebsarzt",
    name: "Betriebsmedizin",
    floor: 1,
    capacity: 4,
    room_type: "office",
    adjacent: ["flur-og"],
    department: "Gesundheit",
  },
};

export const ALL_ROOM_IDS = Object.keys(ROOM_METADATA);
