[package]
name = "sentinel-sandbox"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
anyhow = { workspace = true }
landlock = "0.4"
sentinel-common = { path = "../sentinel-common" }
tracing = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "sandbox_bench"
harness = false
